doctrine:
    dbal:
        # configure these for your database server
        default_connection: default
        connections:
            default:
                driver: 'pdo_mysql'
                server_version: '%env(resolve:MYSQL_VERSION)%'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                # https://symfony.com/doc/current/messenger.html#doctrine-transport
                schema_filter: '~^(?!messenger_messages)~'
                url: '%env(resolve:DATABASE_URL)%'
                mapping_types:
                    enum: string
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
        types:
            datetime: App\General\Domain\Doctrine\DBAL\Types\UTCDateTimeType
            datetimetz: App\General\Domain\Doctrine\DBAL\Types\UTCDateTimeType
            EnumLanguage: App\General\Domain\Doctrine\DBAL\Types\EnumLanguageType
            EnumLocale: App\General\Domain\Doctrine\DBAL\Types\EnumLocaleType
            EnumLogLogin: App\General\Domain\Doctrine\DBAL\Types\EnumLogLoginType
            tm_datetime: App\Shared\Infrastructure\Persistence\Doctrine\DateTimeType
            user_id: App\Shared\Infrastructure\Persistence\Doctrine\UserIdType

            project_id: App\Projects\Infrastructure\Persistence\Doctrine\ProjectIdType
            project_name: App\Projects\Infrastructure\Persistence\Doctrine\ProjectNameType
            project_description: App\Projects\Infrastructure\Persistence\Doctrine\ProjectDescriptionType
            project_finish_date: App\Projects\Infrastructure\Persistence\Doctrine\ProjectFinishDateType
            project_status: App\Projects\Infrastructure\Persistence\Doctrine\ProjectStatusType

            request_id: App\Projects\Infrastructure\Persistence\Doctrine\RequestIdType
            request_status: App\Projects\Infrastructure\Persistence\Doctrine\RequestStatusType
            request_change_date: App\Projects\Infrastructure\Persistence\Doctrine\RequestChangeDateType

            task_id: App\Projects\Infrastructure\Persistence\Doctrine\TaskIdType
            task_name: App\Projects\Infrastructure\Persistence\Doctrine\TaskNameType
            task_brief: App\Projects\Infrastructure\Persistence\Doctrine\TaskBriefType
            task_description: App\Projects\Infrastructure\Persistence\Doctrine\TaskDescriptionType
            task_start_date: App\Projects\Infrastructure\Persistence\Doctrine\TaskStartDateType
            task_finish_date: App\Projects\Infrastructure\Persistence\Doctrine\TaskFinishDateType
            task_status: App\Projects\Infrastructure\Persistence\Doctrine\TaskStatusType

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        default_entity_manager: default
        controller_resolver:
            auto_mapping: false
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                report_fields_where_declared: true
                validate_xml_mapping: true
                connection: default
                mappings:
                    General:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/General/Domain/Entity'
                        prefix: 'App\General\Domain\Entity'
                        alias: General
                    Projects:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Projects/Domain/Entity'
                        prefix: 'App\Projects\Domain\Entity'
                        alias: Projects
                    Projections:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Projections/Domain/Entity'
                        prefix: 'App\Projections\Domain\Entity'
                        alias: Projections
                dql:
                    datetime_functions:
                        datesub: DoctrineExtensions\Query\Mysql\DateSub
                        now: DoctrineExtensions\Query\Mysql\Now
                    string_functions:
                        uuid_o_t_to_bin: App\General\Infrastructure\DQL\UuidOTToBin
                        bin_to_uuid_o_t: App\General\Infrastructure\DQL\BinToUuidOT
                        cast: Oro\ORM\Query\AST\Functions\Cast

when@prod: &not-dev
    doctrine:
        dbal:
            logging: false
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

when@staging: *not-dev

when@test:
    doctrine:
        dbal:
            logging: false
